buah=["Durian","Mangga","Rambutan","Anggur","Pepaya"] 
print('*'*60)
print(buah) 
print("Buah [0] ", buah[0]) 
print("Buah [1] ", buah[1]) 
print("Buah [2:] ", buah[2:]) 
print("Buah [-1] ", buah[-1]) 
print('*'*60)
mylist=["Ternate", 1000, 2000, "Tidore", "Maitara", 3000] 
print("mylist : ", mylist)
print("mylist [:3] : ", mylist[:3])
print("mylist[1] : ", mylist[1]) 
print("mylist[2] : ", mylist[2])
print("mylist[1] + mylist[2] : ", mylist[1] + mylist[2])
print('*'*60) 
